# DEPRECATED: We need to update the scripts to be compatible with the new Quartus build.
# This makefile and the contents of the folder are preserved for further reference.

base_dir=$(abspath ../../hardware/chipyard)
sim_dir=$(abspath .)
common_fpga_dir=$(abspath ..)

SUB_PROJECT ?= arrow

include $(common_fpga_dir)/common.mk
